version: '3.8'
services:
  db:
    image: postgres:15
    container_name: pizza-db
    environment:
      POSTGRES_USER: pizzauser
      POSTGRES_PASSWORD: pizzapw
      POSTGRES_DB: pizza
    ports:
      - "5467:5432"
    networks:
    - default
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api:
    build: .
    container_name: pizza-api
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://pizzauser:pizzapw@db:5432/pizza
      JWT_SECRET: supersecrethdhehehehe
      ADMIN_EMAIL: admin@test.com
      ADMIN_PASSWORD: 12345
      PORT: 3001
    depends_on:
      db:
        condition: service_started
    networks:
    - default
 #   - proxy
 #   labels:
 #     - "traefik.enable=true"
 #     - "traefik.http.routers.pizza.entrypoints=http"
 #     - "traefik.http.routers.pizza.rule=Host(`pizza.stasu.de`)"
 #     - "traefik.http.routers.pizza.middlewares=redirect@file"
 #     - "traefik.http.routers.pizza-secure.entrypoints=https"
 #     - "traefik.http.routers.pizza-secure.rule=Host(`pizza.stasu.de`)"
 #     - "traefik.http.routers.pizza-secure.tls=true"
 #     - "traefik.http.routers.pizza-secure.tls.certresolver=mytlschallenge"
 #     - "traefik.http.routers.pizza-secure.service=pizza"
 #     - "traefik.http.services.pizza.loadbalancer.server.port=3001"
 #     - "traefik.docker.network=proxy"

networks:
  default:
    external : false
#  proxy:
#    external: true